/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/belts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["belts_list"];
        put?: never;
        post: operations["belts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/belts/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["belts_retrieve"];
        put: operations["belts_update"];
        post?: never;
        delete: operations["belts_destroy"];
        options?: never;
        head?: never;
        patch: operations["belts_partial_update"];
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_list"];
        put?: never;
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["categories_retrieve"];
        put: operations["categories_update"];
        post?: never;
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/techniques/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["techniques_list"];
        put?: never;
        post: operations["techniques_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/techniques/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["techniques_retrieve"];
        put: operations["techniques_update"];
        post?: never;
        delete: operations["techniques_destroy"];
        options?: never;
        head?: never;
        patch: operations["techniques_partial_update"];
        trace?: never;
    };
    "/api/variations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["variations_list"];
        put?: never;
        post: operations["variations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/variations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["variations_retrieve"];
        put: operations["variations_update"];
        post?: never;
        delete: operations["variations_destroy"];
        options?: never;
        head?: never;
        patch: operations["variations_partial_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Belt: {
            readonly id: number;
            color: components["schemas"]["ColorEnum"];
            /**
             * Format: int64
             * @description Belt progression order, 1=white, 5=black
             */
            order: number;
        };
        BeltRequest: {
            color: components["schemas"]["ColorEnum"];
            /**
             * Format: int64
             * @description Belt progression order, 1=white, 5=black
             */
            order: number;
        };
        /**
         * @description * `white` - White
         *     * `blue` - Blue
         *     * `purple` - Purple
         *     * `brown` - Brown
         *     * `black` - Black
         * @enum {string}
         */
        ColorEnum: "white" | "blue" | "purple" | "brown" | "black";
        PatchedBeltRequest: {
            color?: components["schemas"]["ColorEnum"];
            /**
             * Format: int64
             * @description Belt progression order, 1=white, 5=black
             */
            order?: number;
        };
        PatchedTechniqueCategoryRequest: {
            name?: string;
            description?: string;
        };
        PatchedTechniqueRequest: {
            name?: string;
            description?: string;
            difficulty?: number;
        };
        PatchedTechniqueVariationRequest: {
            name?: string;
            description?: string;
        };
        Technique: {
            readonly id: number;
            name: string;
            description?: string;
            difficulty?: number;
            readonly min_belt: components["schemas"]["Belt"];
            readonly categories: components["schemas"]["TechniqueCategory"][];
            readonly variations: components["schemas"]["TechniqueVariation"][];
            readonly leads_to: components["schemas"]["TechniqueFlow"][];
        };
        TechniqueCategory: {
            readonly id: number;
            name: string;
            description?: string;
        };
        TechniqueCategoryRequest: {
            name: string;
            description?: string;
        };
        TechniqueFlow: {
            readonly id: number;
            readonly to_technique: string;
            description?: string;
        };
        TechniqueFlowRequest: {
            description?: string;
        };
        TechniqueRequest: {
            name: string;
            description?: string;
            difficulty?: number;
        };
        TechniqueVariation: {
            readonly id: number;
            name: string;
            description?: string;
        };
        TechniqueVariationRequest: {
            name: string;
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    belts_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Belt"][];
                };
            };
        };
    };
    belts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeltRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BeltRequest"];
                "multipart/form-data": components["schemas"]["BeltRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Belt"];
                };
            };
        };
    };
    belts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this belt. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Belt"];
                };
            };
        };
    };
    belts_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this belt. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BeltRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BeltRequest"];
                "multipart/form-data": components["schemas"]["BeltRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Belt"];
                };
            };
        };
    };
    belts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this belt. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    belts_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this belt. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedBeltRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedBeltRequest"];
                "multipart/form-data": components["schemas"]["PatchedBeltRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Belt"];
                };
            };
        };
    };
    categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueCategory"][];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechniqueCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TechniqueCategoryRequest"];
                "multipart/form-data": components["schemas"]["TechniqueCategoryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueCategory"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueCategory"];
                };
            };
        };
    };
    categories_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechniqueCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TechniqueCategoryRequest"];
                "multipart/form-data": components["schemas"]["TechniqueCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueCategory"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique category. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTechniqueCategoryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTechniqueCategoryRequest"];
                "multipart/form-data": components["schemas"]["PatchedTechniqueCategoryRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueCategory"];
                };
            };
        };
    };
    techniques_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technique"][];
                };
            };
        };
    };
    techniques_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechniqueRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TechniqueRequest"];
                "multipart/form-data": components["schemas"]["TechniqueRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technique"];
                };
            };
        };
    };
    techniques_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technique"];
                };
            };
        };
    };
    techniques_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechniqueRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TechniqueRequest"];
                "multipart/form-data": components["schemas"]["TechniqueRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technique"];
                };
            };
        };
    };
    techniques_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    techniques_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTechniqueRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTechniqueRequest"];
                "multipart/form-data": components["schemas"]["PatchedTechniqueRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technique"];
                };
            };
        };
    };
    variations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueVariation"][];
                };
            };
        };
    };
    variations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechniqueVariationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TechniqueVariationRequest"];
                "multipart/form-data": components["schemas"]["TechniqueVariationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueVariation"];
                };
            };
        };
    };
    variations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique variation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueVariation"];
                };
            };
        };
    };
    variations_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique variation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TechniqueVariationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TechniqueVariationRequest"];
                "multipart/form-data": components["schemas"]["TechniqueVariationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueVariation"];
                };
            };
        };
    };
    variations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique variation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    variations_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this technique variation. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTechniqueVariationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTechniqueVariationRequest"];
                "multipart/form-data": components["schemas"]["PatchedTechniqueVariationRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechniqueVariation"];
                };
            };
        };
    };
}
